config/routes.rb
Rails.application.routes.draw do

  root to: 'combatants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :combatants

  resources :fighters, only: [ :create, :destroy ] do
    member do
      post 'add_weapon'
      post 'add_shield'
      post 'add_spell'
    end
  end

  resources :fights, only: [:show, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/combatant.rb
class Combatant < ApplicationRecord

  has_many :fighters

  # before_update :reload_life, if: :life_changed?
  # before_update :set_previous_life, if: :life_changed?
  # before_update :set_previous_attack, if: :attack_changed?

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :life, presence: true, numericality: { only_integer: true, greater_or_equal_to: 15 }
  validates :life, presence: true, numericality: { only_integer: true, less_than_or_equal_to: 20 }
  validates :attack, presence: true, numericality: { only_integer: true, greater_or_equal_to: 2 }
  validates :attack, presence: true, numericality: { only_integer: true, less_than_or_equal_to: 4 }
  validates :experience, presence: true, numericality: { only_integer: true, greater_or_equal_to: 25 }
  validates :experience, presence: true, numericality: { only_integer: true, less_than_or_equal_to: 50 }
  validates :image_url, allow_blank: true, format:{
    with:    %r{\.(jpg||png||gif)\Z}i,
    message: 'doit être une url vers une image GIF, JPG ou PNG'
  }

  # def reload_life
  #   write_attribute(:first_life, reload!)
  # end

  # def set_previous_life
  #   write_attribute(:previous_life, life_was)
  # end

  # def set_previous_attack
  #   write_attribute(:previous_attack, attack_was)
  # end

end

app/models/fight.rb
class Fight < ApplicationRecord

  has_many :fighters, dependent: :destroy

  def add_combatant(combatant)
    current_fighter = fighters.find_by(combatant_id: combatant.id)
    if current_fighter.nil? && fighters.size < 2
      current_fighter = fighters.build(combatant_id: combatant.id)
    end
  end

  def add_fighters(fight)
    fight.fighters.each do |fighter|
      fighter.fight_id = nil
      fighters << fighter
    end
  end

  def run
    fighter1 = fighters.first
    fighter2 = fighters.second
    combatant1 = fighter1.combatant
    combatant2 = fighter2.combatant
    while (combatant1.life > combatant2.attack) && (combatant2.life > combatant1.attack)
      combatant2.life -= combatant1.attack
      combatant1.life -= combatant2.attack
    end
    if combatant1.life > combatant2.life
      combatant1.experience += 2
    elsif combatant1.life < combatant2.life
      combatant2.experience += 2
    elsif combatant1.life == combatant2.life
      combatant1.experience += 2
      combatant2.experience += 2
    end
    combatant1.save
    combatant2.save
  end

end

app/models/fighter.rb
class Fighter < ApplicationRecord

  belongs_to :combatant
  belongs_to :fight

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_fight

  private

    def current_fight
      if !session[:fight_id].nil?
        Fight.find(session[:fight_id])
      else
        Fight.new
      end
      rescue ActiveRecord::RecordNotFound
        Fight.new
    end
end

app/controllers/combatants_controller.rb
class CombatantsController < ApplicationController

  before_action :set_combatant, only: [:show, :edit, :update, :destroy]

  def index
    @combatants = Combatant.order(id: :asc)
  end

  def show
  end

  def new
    @combatant = Combatant.new
  end

  def create
    @combatant = Combatant.new(combatant_params)
    if @combatant.save
      redirect_to combatants_url, notice: "Nouveau combattant créé"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @combatant.update(combatant_params)
      redirect_to combatant_url(@combatant), notice: "Combattant modifié"
    else
      render :edit
    end
  end

  def destroy
    @combatant.destroy
    redirect_to combatants_url, alert: "Combattant supprimé"
  end

  private

  def set_combatant
    @combatant = Combatant.find(params[:id])
  end

  def combatant_params
    params.require(:combatant).permit(:name, :life, :attack, :experience, :image_url)
  end

end

app/controllers/fighters_controller.rb
class FightersController < ApplicationController

  before_action :set_fight

  before_action :set_fighter, except: [:create]

  def create
    combatant = Combatant.find(params[:combatant_id])
    @fighter = @fight.add_combatant(combatant)
    respond_to do |format|
      if !@fighter.nil? && @fighter.save
        format.html { redirect_back fallback_location: combatants_url, notice: "Combattant envoyé dans l'arène !" }
        format.js { flash.now[:notice] = "Combattant envoyé dans l'arène !" }
      elsif @fight.fighters.size == 2
        format.html { redirect_back fallback_location: combatants_url, alert: "2 Combattants déjà parés au combat !" }
        format.js { flash.now[:alert] = "2 Combattants déjà parés au combat !" }
      else
        format.html { redirect_back fallback_location: combatants_url, alert: "Combattant déjà dans l'arène !" }
        format.js { flash.now[:alert] = "Combattant déjà dans l'arène !" }
      end
    end
    @fight.save
    session[:fight_id] = @fight.id
  end

  def add_weapon
    @combatant = @fighter.combatant
    respond_to do |format|
      if @combatant.attack < 3
        @combatant.update_attribute(:attack, @combatant.attack += 1)
        format.html { redirect_back fallback_location: combatants_url, notice: "Cool, #{@combatant.name} gagne 1 points d'attaque !" }
        format.js { flash.now[:notice] = "Cool, #{@combatant.name} gagne 1 points d'attaque !" }
      end
    end
  end

  def add_shield
    @combatant = @fighter.combatant
    respond_to do |format|
      if @combatant.life >= 5 && @combatant.life < 15
        @combatant.update_attribute(:life, @combatant.life += 5)
        format.html { redirect_back fallback_location: combatants_url, notice: "Cool, #{@combatant.name} gagne 5 points de vie !" }
        format.js { flash.now[:notice] = "Cool, #{@combatant.name} gagne 5 points de vie !" }
      end
    end
  end

  def add_spell
    @combatant = @fighter.combatant
    respond_to do |format|
      if @combatant.life < 5
        @combatant.update_attribute(:life, 18)
        format.html { redirect_back fallback_location: combatants_url, notice: "Cool, #{@combatant.name} se refait une santé !" }
        format.js { flash.now[:notice] = "Cool, #{@combatant.name} se refait une santé !" }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @fighter.destroy
        format.html { redirect_back fallback_location: combatants_url, alert: "Combattant sorti de l'arène !" }
        format.js { flash.now[:alert] = "Combattant sorti de l'arène !" }
      end
    end
    @fighters = @fight.fighters
  end

  private

    def set_fight
      @fight = current_fight
    end

    def set_fighter
      @fighter = @fight.fighters.find(params[:id])
    end

end

app/controllers/fights_controller.rb
class FightsController < ApplicationController

  def show
    @fight= Fight.find(params[:id])
    fighter1 = @fight.fighters.first
    fighter2 = @fight.fighters.second
    combatant1 = fighter1.combatant
    combatant2 = fighter2.combatant
    if combatant1.life > combatant2.life
      @winner = combatant1
      @looser = combatant2
    elsif combatant1.life < combatant2.life
      @winner = combatant2
      @looser = combatant1
    elsif combatant1.life == combatant2.life
      @winner1 = combatant1
      @winner2 = combatant2
    end
  end

  def create
    @final_fight = Fight.new
    #fighters go from the current_fight to the final fight
    @final_fight.add_fighters(current_fight)
    if @final_fight.save
      #start final fight
      @final_fight.run
      # destroy cart
      Fight.destroy(session[:fight_id])
      session[:fight_id] = nil
      redirect_to fight_url(@final_fight)
    else
      render "combatants/index"
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/combatants/_combatant.html.erb
<div class="combatant-card-<%= combatant.id %>">
  <div class="combatant">
    <div class='combatant-id'>
      <div class='combatant-count'><%= combatant.id %></div>
    </div>

    <% if !combatant.image_url.blank? %>
      <%= image_tag combatant.image_url, alt:"Combattant", class:"combatant-image hidden-xs" %>
    <% else %>
      <%= image_tag "https://scontent-amt2-1.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/c0.135.1080.1080/18299818_463781843955344_8661087945098264576_n.jpg", alt:"Combattant", class:"combatant-image hidden-xs" %>
    <% end %>

    <div class='combatant-body'>
      <h3><%= link_to combatant.name, combatant_path(combatant) %></h3>
    </div>

    <div class="combatant-details">
      <h5>
        <%= button_to "Vs", fighters_path(combatant_id: combatant.id), remote: true, method: :post, class: "btn btn-primary" %>
      </h5>
    </div>

    <ul class="list-inline combatant-controls">
      <li>
        <a><i class="fa fa-heart fa-2x"></i></a><br>
        <p><%= combatant.life %></p>
      </li>
      <li>
        <a><i class="fa fa-bolt fa-2x"></i></a><br>
        <p><%= combatant.attack %></p>
      </li>
    </ul>
  </div>
</div>

app/views/combatants/_fight_bill.html.erb
<div class="row">
  <% current_fight.fighters.each do |fighter| %>
    <div class="col-xs-12 col-md-6">
      <div class="fighter_card">
        <div class="fighter_card-category">
          Expérience <span class="label label-primary"><%= fighter.combatant.experience %></span><br>
        </div>

        <div class="fighter_card-description">
          <h2><%= fighter.combatant.name %></h2>
          <p>
            Vie <span class="label label-primary"><%= fighter.combatant.life %></span>
          </p>
        </div>
        <div class="fighter_card-attack">
          <p>
            Attaque <span class="label label-danger"><%= fighter.combatant.attack %></span>
          </p>
        </div>

        <% if !fighter.combatant.image_url.blank? %>
          <%= image_tag fighter.combatant.image_url, alt:"Combattant", class:"fighter_card-combatant avatar-large" %>
        <% else %>
          <%= image_tag "https://scontent-amt2-1.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/c0.135.1080.1080/18299818_463781843955344_8661087945098264576_n.jpg", alt:"Combattant", class:"fighter_card-combatant avatar-large"%>
        <% end %>

      </div>
      <div id="add-equipment">
        <% if fighter.combatant.attack < 3 %>
          <p>
          <%= link_to add_weapon_fighter_path(fighter), method: :post, remote: true do %>
            Une arme <i class="fa fa-bomb"></i>
          <% end %>
        <% end %>
        <% if fighter.combatant.life >= 5 && fighter.combatant.life < 15 %>
          <%= link_to add_shield_fighter_path(fighter), method: :post, remote: true do %>
            Un Bouclier <i class="fa fa-shield"></i>
          <% end %>
          </p>
        <% end %>
        <% if fighter.combatant.life < 5 %>
          <p>
            <%= link_to add_spell_fighter_path(fighter), method: :post, remote: true do %>
              Régénère les pts de vie <i class="fa fa-magic"></i>
            <% end %>
          </p>
        <% end %>
      </div>
      <p>
        <%= link_to "Sortir de l'arène", fighter, data: { confirm: "Êtes-vous sûr de sortir '#{fighter.combatant.name}' de l'arène ?" }, method: :delete, remote: true %>
      </p>
    </div>
  <% end %>
</div>

<div class="run-fight">
  <% if current_fight.fighters.size == 2 %>
    <%= link_to "Démarre le combat", fights_path, method: :post, class:"btn btn-danger btn-lg" %>
  <% end %>
</div>

app/views/combatants/_form.html.erb
<%= simple_form_for @combatant do |f| %>

  <% if !@combatant.nil? && @combatant.errors.any? %>
    <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <ul>
      <% @combatant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :name, label: "Nom" %>
    <%= f.input :life, label: "Points de vie", collection: 15..20  %>
    <%= f.input :attack, label: "Points d'attaque", collection: 2..4  %>
    <%= f.input :experience, label: "Expérience", collection: 25..50  %>
  </div>

  <div class="form-inputs">
    <%= f.input :image_url, label: "Avatar (trouve une tofe en ligne)", placeholder: "http://www.maphoto.jpg, .png, .gif" %>
  </div>

  <p>&nbsp</p>

  <div class="form-actions">
    <% if f.object.new_record? %>
      <%= f.button :button, "Créer".html_safe, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i>"}, class: "btn btn-success btn-lg"%>
    <% else %>
      <%= f.button :button, "Modifier".html_safe, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i>"}, class: "btn btn-success btn-lg"%>
    <% end %>

    <%= link_to "Annuler", root_url, class: "btn btn-default btn-lg" %>
  </div>

<% end %>

app/views/combatants/edit.html.erb
<div class="container padded text-center">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h2 class="text-center">Modifier ce combattant</h2>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/combatants/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "background.jpg" %>');">
  <div class="banner-content">
    <h1>CROLLS</h1>
    <h2>L'ultime combat</h2>
    <p>
      À chaque nouvelle lune, les clans des terres brunes se mesurent lors de combats éclairs<br>
      Leur puissance est telle que les attaques échappent au commun des mortels<br>
      Choisis les guerriers qui vont s'affronter
    </p>
    <a href="#warriors", class="btn btn-primary btn-lg">Entre dans l'arène !</a>
  </div>
</div>

<div class="container padded text-center">

  <h3 id="warriors", style="outline: none;">
    Fais combattre 2 guerriers, clique sur <span class="btn btn-primary">Vs</span>
  </h3>

  <div class="flash"></div>

  <div class="text-center fight-bill"">
    <%= render "fight_bill" %>
  </div>

</div>

<div class="container">
  <%= link_to new_combatant_path do %>
    <i class="fa fa-plus"></i> Créer un guerrier
  <% end %>

  <p>&nbsp</p>

  <% @combatants.each do |combatant| %>
    <%= render 'combatant', combatant: combatant %>
  <% end %>
</div>

app/views/combatants/new.html.erb
<div class="container padded text-center">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h2 class="text-center">Créer un combattant</h2>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/combatants/show.html.erb
<div class="combatant-description container">

  <p class="text-left">
    <%= link_to "Modifie son profil", edit_combatant_path(@combatant), class: "btn btn-primary" %> <%= link_to "Supprime ce combattant", combatant_path(@combatant), method: :delete, data: {confirm: 'Êtes-vous sûr de vouloir supprimer ce guerrier ?'}, class: "btn btn-danger" %>
  </p>

  <div class="combatant-avatar container text-center padded">
    <div class="row">
      <div class="col-xs-12">
        <% if !@combatant.image_url.blank? %>
          <%= image_tag @combatant.image_url, alt:"Combattant", class:"avatar-extra-large" %>
        <% else %>
          <%= image_tag "https://scontent-amt2-1.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/c0.135.1080.1080/18299818_463781843955344_8661087945098264576_n.jpg", alt:"Combattant", class:"avatar-extra-large" %>
        <% end %>

        <h1 class="combatant-identity">
        <%= @combatant.name %>
        </h1>

        <p class="combatant-identity">
          VIE : <span class="label label-primary"><%= @combatant.life %></span>  points
        </p>
        <p class="combatant-identity">
          ATTAQUE : <span class="label label-primary"><%= @combatant.attack %></span> points
        </p>
        <p class="combatant-identity">
          EXPÉRIENCE : <span class="label label-primary"><%= @combatant.experience %></span> points
        </p>
      </div>
    </div>
  </div>

  <p>&nbsp</p>

  <p>
    <%= link_to "Retour aux combattants", combatants_path, class: "btn btn-default" %>
  </p>

</div>

app/views/fighters/add_shield.js.erb
$(".fight-bill").html("<%= j render 'combatants/fight_bill', fighter: @fighter %>")
$(".combatant-card-<%= @combatant.id %>").html("<%= j render 'combatants/combatant', combatant: @combatant %>")
$(".flash").html("<%= j render 'shared/flashes' %>")

app/views/fighters/add_spell.js.erb
$(".fight-bill").html("<%= j render 'combatants/fight_bill', fighter: @fighter %>")
$(".combatant-card-<%= @combatant.id %>").html("<%= j render 'combatants/combatant', combatant: @combatant %>")
$(".flash").html("<%= j render 'shared/flashes' %>")

app/views/fighters/add_weapon.js.erb
$(".fight-bill").html("<%= j render 'combatants/fight_bill', fighter: @fighter %>")
$(".combatant-card-<%= @combatant.id %>").html("<%= j render 'combatants/combatant', combatant: @combatant %>")
$(".flash").html("<%= j render 'shared/flashes' %>")

app/views/fighters/create.js.erb
$(".fight-bill").html("<%= j render 'combatants/fight_bill' %>")
$(".flash").html("<%= j render 'shared/flashes' %>")

app/views/fighters/destroy.js.erb
$(".fight-bill").html("<%= j render 'combatants/fight_bill' %>")
$(".flash").html("<%= j render 'shared/flashes' %>")

app/views/fights/show.html.erb
<div class="padded text-center fight">
  <% if !@winner1 && !@winner2 %>
    <h1>
      <i class="fa fa-star-o fa-2x"></i><i class="fa fa-star-o fa-2x"></i><i class="fa fa-star-o fa-2x"></i><i class="fa fa-star-o fa-2x"></i>
      <p>&nbsp</p>
      AND THE WINNER IS...<br>
    </h1>
    <h1>
      <i class="fa fa-bolt fa-2x"></i>
      <%= @winner.name %>
      <i class="fa fa-bolt fa-2x"></i>
    </h1>
    <br>
    <p>
      Points de vie restants : <span class="btn btn-warning"><%= @winner.life%></span><br>
      <%= @winner.name %> remporte <span class="btn btn-primary">2</span> points d'expérience <br>
    </p>
    <h2>
      <%= @looser.name %> perd son combat
    </h2>
    <p>
      Points de vie restants : <span class="btn btn-warning"><%= @looser.life%></span><br>
    </p>
    <br>
    <p>
     Pense à régénérer les combattants avant leur prochain combat... <br>
    </p>
  <% else %>
    <h1>
      <i class="fa fa-star-o fa-2x"></i><i class="fa fa-star-o fa-2x"></i><i class="fa fa-star-o fa-2x"></i><i class="fa fa-star-o fa-2x"></i>
      <p>&nbsp</p>
      EX AEQUO...<br>
    </h1>
    <h1>
      <i class="fa fa-bolt fa-2x"></i>
      <%= @winner1.name %> &
      <%= @winner2.name %>
      <i class="fa fa-bolt fa-2x"></i>
    </h1>
    <br>
    <p>
      <%= @winner1.name %> remporte <span class="btn btn-primary">2</span> points d'expérience <br>
      Points de vie restants : <span class="btn btn-warning"><%= @winner1.life%></span><br>
    </p>
    <p>
      <%= @winner2.name %> remporte aussi <span class="btn btn-primary">2</span> points d'expérience <br>
      Points de vie restants : <span class="btn btn-warning"><%= @winner1.life%></span><br>
    </p>

  <% end %>
    <p>
     <%= link_to "Retourne à l'arène", combatants_path, class: "btn btn-primary" %>
    </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>CROLLS</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>